networks:
  menu-maker-network:
    name: menu-maker-network
    driver: bridge

services:
  menu-maker-database:
    container_name: menu-maker-database
    image: postgres:16-alpine
    user: postgres
    ports:
      - "9000:5432"
    volumes:
      - menu_maker_volume:/var/lib/postgresql/data
    env_file:
      - .env.database
    networks:
      - menu-maker-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "menuMaker"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

volumes:
  menu_maker_volume:
    name: menu_maker_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./var/postgres/data