networks:
  menu-maker-network:
    name: menu-maker-network
    driver: bridge

services:
  menu-maker-database:
    container_name: menu-maker-database
    image: postgres:16-alpine
    user: postgres
    ports:
      - "9000:5432"
    volumes:
      - ./var/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PASSWORD=senhaforte123
      - POSTGRES_DB=menuMaker
      - POSTGRES_USER=postgres
      - POSTGRES_PORT=5432
      - TZ=UTC
    networks:
      - menu-maker-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "menuMaker"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s